'''import turtle
pen = turtle.Turtle()
pen.speed(0.8)
pen.color('red')
pen.pensize(3)

pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.forward(100)

pen.penup()
pen.goto(-500, 0)
pen.pendown()

pen.circle(50, 180)

turtle.done()'''
# draws the word "YOKES" 
import turtle
pen = turtle.Turtle()
pen.speed(0)
pen.color('black', 'red')
pen.pensize(4)

# Y
pen.penup()
pen.goto(0, 10)
pen.setheading(90)  
pen.pendown()
pen.left(45)
pen.forward(50)
pen.penup()
pen.goto(0,10)
pen.setheading(90)
pen.pendown()
pen.right(45)
pen.forward(50)
pen.penup()
pen.goto(0, 10)
pen.setheading(0)
pen.pendown()
pen.right(90)
pen.forward(50)
# O
pen.penup()
pen.goto(50, -10)
pen.pendown()
pen.circle(25)
pen.penup()
pen.forward(60)
#K
pen.left(90)
pen.penup()
pen.goto(140,-30)
pen.pendown()
pen.left(90)
pen.forward(60)
pen.backward(30)
pen.right(45)
pen.forward(40)
pen.backward(40)
pen.right(90)
pen.forward(40)
pen.penup()
pen.left(135)
pen.forward(40)
#E
pen.right(90)
pen.penup()
pen.goto(200,25)
pen.pendown()
pen.forward(40)
pen.backward(40)
pen.right(90)
pen.forward(30)
pen.left(90)
pen.forward(30)
pen.backward(30)
pen.right(90)
pen.forward(30)
pen.left(90)
pen.forward(40)
pen.penup()
pen.forward(20)
#S
pen.goto(270,25)
pen.pendown()
pen.forward(40)
pen.backward(40)
pen.right(90)
pen.forward(30)
pen.left(90)
pen.forward(40)
pen.right(90)
pen.forward(30)
pen.right(90)
pen.forward(40)
pen.penup()
pen.left(90)
pen.forward(60)
#H
pen.right(90)
pen.goto(370,25)
pen.pendown()
pen.left(90)
pen.forward(60)
pen.backward(30)
pen.right(90)
pen.forward(30)
pen.left(90)
pen.forward(30)
pen.backward(60)
pen.penup()
pen.right(90)
pen.forward(40)



turtle.done()
